config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'entries#index'
  resources :entries, only: [:create, :new, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

    def index
      @entries = Entry.all
    end
  
    def new
      @entry = Entry.new()
    end
  
    def create
      @entry = Entry.new(entry_params)
      if @entry.save
        redirect_to root_url
      else
        render :new
      end
    end 
  
    def destroy
      Entry.find(params[:id]).destroy
      redirect_to root_url
    end
  
    private
  
    def entry_params
      params.require(:entry).permit(:name)
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/index.html.erb
<h1>All Entries</h1>

<div>
 <% @entries.each do |entry| %>
   <%= entry.name %>
   <%= button_to "Delete", entry, method: :delete, data: { confirm: "Are you sure you want to delete this Project ?"} %>
 <% end %>
</div>

app/views/entries/new.html.erb
<h1>New Entry</h1>
<%= form_with(model: @entry) do |form| %>

 <div>
   <%= form.label :name %>
   <%= form.text_field :name %>
 </div>

  <div>
   <%= form.submit %>
  </div>

  <br>

  <div> 
    <%= link_to "Back to home", root_path %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Journal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render '/shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div>
 <div>
   <%= link_to "Ruby learning journal", root_path %>

   <div class="navbar-link">
     <%= link_to "New Entry", new_entry_path %>
   </div>

 </div>
</div>